"""initial_tables

Revision ID: d6705e4ea030
Revises: 
Create Date: 2026-03-27 07:48:57.620684

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd6705e4ea030'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('emergency_contact', sa.String(length=100), nullable=True),
    sa.Column('medical_notes', sa.Text(), nullable=True),
    sa.Column('care_level', sa.Integer(), nullable=True),
    sa.Column('certification_number', sa.String(length=50), nullable=True),
    sa.Column('specialization', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_receiver_id'), 'messages', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_id'), 'messages', ['sender_id'], unique=False)
    op.create_table('qr_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('purpose', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('max_uses', sa.Integer(), nullable=False),
    sa.Column('use_count', sa.Integer(), nullable=False),
    sa.Column('allowed_ip_addresses', postgresql.ARRAY(postgresql.INET()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_qr_tokens_expires_at'), 'qr_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_qr_tokens_token_hash'), 'qr_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('ix_qr_tokens_user_id'), 'qr_tokens', ['user_id'], unique=False)
    op.create_table('recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('cooking_time', sa.Integer(), nullable=False),
    sa.Column('ingredients', sa.Text(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('recipe_url', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_category'), 'recipes', ['category'], unique=False)
    op.create_index(op.f('ix_recipes_type'), 'recipes', ['type'], unique=False)
    op.create_index(op.f('ix_recipes_user_id'), 'recipes', ['user_id'], unique=False)
    op.create_table('shopping_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('senior_user_id', sa.UUID(), nullable=False),
    sa.Column('helper_user_id', sa.UUID(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['helper_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['senior_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_requests_helper_user_id'), 'shopping_requests', ['helper_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_requests_request_date'), 'shopping_requests', ['request_date'], unique=False)
    op.create_index(op.f('ix_shopping_requests_senior_user_id'), 'shopping_requests', ['senior_user_id'], unique=False)
    op.create_index(op.f('ix_shopping_requests_status'), 'shopping_requests', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('senior_user_id', sa.UUID(), nullable=False),
    sa.Column('helper_user_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('task_type', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=True),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('scheduled_start_time', sa.Time(), nullable=True),
    sa.Column('scheduled_end_time', sa.Time(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['helper_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['senior_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_helper_user_id'), 'tasks', ['helper_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_scheduled_date'), 'tasks', ['scheduled_date'], unique=False)
    op.create_index(op.f('ix_tasks_senior_user_id'), 'tasks', ['senior_user_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_table('weekly_menus',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('week_start', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'week_start')
    )
    op.create_index(op.f('ix_weekly_menus_user_id'), 'weekly_menus', ['user_id'], unique=False)
    op.create_index(op.f('ix_weekly_menus_week_start'), 'weekly_menus', ['week_start'], unique=False)
    op.create_table('shopping_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopping_request_id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('quantity', sa.String(length=50), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shopping_request_id'], ['shopping_requests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shopping_items_shopping_request_id'), 'shopping_items', ['shopping_request_id'], unique=False)
    op.create_table('task_completions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('helper_user_id', sa.UUID(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('next_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['helper_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_completions_helper_user_id'), 'task_completions', ['helper_user_id'], unique=False)
    op.create_index(op.f('ix_task_completions_task_id'), 'task_completions', ['task_id'], unique=False)
    op.create_table('weekly_menu_recipes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('weekly_menu_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('meal_type', sa.String(length=10), nullable=False),
    sa.Column('recipe_type', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['weekly_menu_id'], ['weekly_menus.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('weekly_menu_id', 'day_of_week', 'meal_type', 'recipe_type')
    )
    op.create_index(op.f('ix_weekly_menu_recipes_recipe_id'), 'weekly_menu_recipes', ['recipe_id'], unique=False)
    op.create_index(op.f('ix_weekly_menu_recipes_weekly_menu_id'), 'weekly_menu_recipes', ['weekly_menu_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weekly_menu_recipes_weekly_menu_id'), table_name='weekly_menu_recipes')
    op.drop_index(op.f('ix_weekly_menu_recipes_recipe_id'), table_name='weekly_menu_recipes')
    op.drop_table('weekly_menu_recipes')
    op.drop_index(op.f('ix_task_completions_task_id'), table_name='task_completions')
    op.drop_index(op.f('ix_task_completions_helper_user_id'), table_name='task_completions')
    op.drop_table('task_completions')
    op.drop_index(op.f('ix_shopping_items_shopping_request_id'), table_name='shopping_items')
    op.drop_table('shopping_items')
    op.drop_index(op.f('ix_weekly_menus_week_start'), table_name='weekly_menus')
    op.drop_index(op.f('ix_weekly_menus_user_id'), table_name='weekly_menus')
    op.drop_table('weekly_menus')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_senior_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_scheduled_date'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_helper_user_id'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_shopping_requests_status'), table_name='shopping_requests')
    op.drop_index(op.f('ix_shopping_requests_senior_user_id'), table_name='shopping_requests')
    op.drop_index(op.f('ix_shopping_requests_request_date'), table_name='shopping_requests')
    op.drop_index(op.f('ix_shopping_requests_helper_user_id'), table_name='shopping_requests')
    op.drop_table('shopping_requests')
    op.drop_index(op.f('ix_recipes_user_id'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_type'), table_name='recipes')
    op.drop_index(op.f('ix_recipes_category'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_qr_tokens_user_id'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_token_hash'), table_name='qr_tokens')
    op.drop_index(op.f('ix_qr_tokens_expires_at'), table_name='qr_tokens')
    op.drop_table('qr_tokens')
    op.drop_index(op.f('ix_messages_sender_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
